--- 
version: "3.0"
services: 
  grafana: 
    depends_on: 
      - prometheus
    image: "grafana/grafana:5.1.2"
    network_mode: host
    ports: 
      - "3000:3000"
    restart: always
  prometheus: 
    image: "prom/prometheus:v2.2.1"
    network_mode: host
    user: $UID
    ports: 
      - "9090:9090"
    restart: always
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    volumes: 
      - "$PWD/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "$PWD/data:/prometheus:rw"
  nginx:
    image: nginx
    network_mode: host
    restart: always
    depends_on: 
      - prometheus
      - grafana
    volumes: 
      - "$PWD/nginx.conf:/etc/nginx/nginx.conf:ro"
 
